# Generated by Django 2.2.4 on 2019-08-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.BigIntegerField()),
                ('descricao', models.CharField(max_length=50)),
                ('cbo', models.BigIntegerField()),
            ],
            options={
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.BigIntegerField()),
                ('descricao', models.CharField(max_length=50)),
                ('ativo', models.CharField(default=1, max_length=1)),
            ],
            options={
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.BigIntegerField()),
                ('descricao', models.CharField(max_length=50)),
                ('cnpj', models.BigIntegerField()),
                ('ativo', models.CharField(default=1, max_length=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.Empresa')),
            ],
            options={
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.BigIntegerField()),
                ('descricao', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.Empresa')),
            ],
            options={
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.BigIntegerField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('data_admissao', models.DateField()),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.Cargo')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.Filial')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.Setor')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
