# Generated by Django 2.2.4 on 2019-08-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='ativo',
        ),
    ]
