# Generated by Django 2.2.4 on 2019-08-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_empresa_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
